### ISSUE TITLE
can i use in upr render?

### ISSUE THREAD

**Issue by marlene8810** [ruccho/WaterRW#2]
HI! THANK tou for this work !

can i use this project  in upr render? 
thanks!

**Comment by marlene8810** [comment]
> HI! THANK tou for this work !
> 
> can i use this project in upr render? thanks!

**Comment by zSynctic** [comment]
does it work?

**Comment by ruccho** [comment]
WaterRW uses GrabPass, which is a feature only available in BuiltinRP, to display reflections on surfaces. 
Using WaterRW in SRP (URP) requires some modifications to your rendering pipelines, but it will be highly project-dependent, making it difficult to provide a unified solution.
Thanks.
