### ISSUE TITLE
can you teach how to use thus package  in urp project in unity?

### ISSUE THREAD

**Issue by marlene8810** [ruccho/WaterRW#3]
thank u ! 
i have some question!🎃 
can you teach how  to use in urp ? thank~

**Comment by naved1197** [comment]
It would be really helpful if we could use this for a URP project.

**Comment by ruccho** [comment]
I'm not planning to support URP (SRP).

See https://github.com/ruccho/WaterRW/issues/2#issuecomment-1623723618 : 
> WaterRW uses GrabPass, which is a feature only available in BuiltinRP, to display reflections on surfaces.
Using WaterRW in SRP (URP) requires some modifications to your rendering pipelines, but it will be highly project-dependent, making it difficult to provide a unified solution.

**Comment by naved1197** [comment]
Okay, thanks for the reply. Great work though we need people like you
